/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.CustomerBooking;

import Business.Airliners;
import Business.AirlinersDirectory;
import Business.FlightScheDirectory;
import Business.Flights;
import Business.PassengerDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userInterface.ManageTravelAgency.listFlightJPanel;
import userInterface.ManageTravelAgency.mngTravelAgencyFrontPageJPanel;

/**
 *
 * @author adhar
 */
public class manageCustJPanel extends javax.swing.JPanel {
    private FlightScheDirectory flightScheDirectory;
    private AirlinersDirectory airlinersDirectory;
    //private Airliners airliners;
    private JPanel rightJPanel;
    private PassengerDirectory passengerDirectory;
    private Flights flights;
    private Flights flight;
    /**
     * Creates new form manageCustJPanel
     */
    

    public manageCustJPanel(JPanel rightJPanel, FlightScheDirectory flightScheDirectory, PassengerDirectory passengerDirectory, Flights flights) {
        initComponents();
      //   this.airliners = airliners;
        this.flightScheDirectory = flightScheDirectory;
      // this.airlinersDirectory = new AirlinersDirectory();
        this.rightJPanel = rightJPanel;
        this.passengerDirectory = passengerDirectory;
        this.flights = flights;
        this.flight = flight;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchBestBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        searchBestBtn.setText("Search Best Flight");
        searchBestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBestBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Best Flight");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(searchBestBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(jLabel1)))
                .addContainerGap(355, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(173, 173, 173)
                .addComponent(searchBestBtn)
                .addContainerGap(350, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchBestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBestBtnActionPerformed
        // TODO add your handling code here:
        bestFlightJPanel panel = new bestFlightJPanel(rightJPanel , flightScheDirectory, passengerDirectory, flights );
        rightJPanel.add("bestFlightJPanel", panel);
        CardLayout layout = (CardLayout)rightJPanel.getLayout();
        layout.next(rightJPanel);
        
      /*  listFlightJPanel list = new listFlightJPanel(rightJPanel, flightScheDirectory);
        rightJPanel.add("listFlightJPanel", list );
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.next(rightJPanel);*/
    }//GEN-LAST:event_searchBestBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton searchBestBtn;
    // End of variables declaration//GEN-END:variables
}

