/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.manageAirlinersJPanel;

import Business.Airliners;
import Business.AirlinersDirectory;
import Business.Airplane;
import Business.FlightScheDirectory;
import Business.Flights;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rohan
 */
public class addFlightJPanel extends javax.swing.JPanel {
    private JPanel rightJPanel;
    //private AirlinersDirectory airlinersDirectory;
    private Airliners airliner;
    private Airplane airplane1;
     private FlightScheDirectory flightScheDirectory;
     //private String airlineName;
    // private Flights flight;
    /**
     * Creates new form addFlightJPanel
     */
    

    addFlightJPanel(JPanel rightJPanel, FlightScheDirectory flightScheDirectory, Airliners airliner, Airplane airplane1) {
         //To change body of generated methods, choose Tools | Templates.
         initComponents();
         this.rightJPanel = rightJPanel;
         //this.airlineName = airlineName;
         this.airplane1 = airplane1;
         this.airliner = airliner;
         airlinerTextField.setText(airliner.getAirlinersName());
         planeNameTextField.setText(airplane1.getAirplaneName());
         //this.airlinersDirectory = airlinersDirectory;
         this.flightScheDirectory = flightScheDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        airlinerTextField = new javax.swing.JTextField();
        idTextField = new javax.swing.JTextField();
        dateTextField = new javax.swing.JTextField();
        fromTextField = new javax.swing.JTextField();
        priceTextField = new javax.swing.JTextField();
        toTextField = new javax.swing.JTextField();
        addFlightBtn = new javax.swing.JButton();
        morningBtn = new javax.swing.JRadioButton();
        eveningBtn = new javax.swing.JRadioButton();
        nightBtn = new javax.swing.JRadioButton();
        backBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        planeNameTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("ADD FLIGHT");

        jLabel2.setText("Airliner");

        jLabel3.setText("Flight ID");

        jLabel4.setText("Departure Time");

        jLabel5.setText("Departure Date(DD/MM/YYY)");

        jLabel6.setText("From ");

        jLabel7.setText("To");

        jLabel8.setText("Price");

        airlinerTextField.setEnabled(false);

        addFlightBtn.setText("Add");
        addFlightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFlightBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(morningBtn);
        morningBtn.setText("MORNING");

        buttonGroup1.add(eveningBtn);
        eveningBtn.setText("EVENING");

        buttonGroup1.add(nightBtn);
        nightBtn.setText("NIGHT");

        backBtn.setText("<<Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel9.setText("Airplane name :");

        planeNameTextField.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(backBtn)
                        .addGap(290, 290, 290)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(8, 8, 8))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(addFlightBtn)
                                    .addComponent(morningBtn))
                                .addGap(18, 18, 18)
                                .addComponent(eveningBtn)
                                .addGap(18, 18, 18)
                                .addComponent(nightBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(224, 224, 224)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(airlinerTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                    .addComponent(idTextField)
                                    .addComponent(dateTextField)
                                    .addComponent(fromTextField)
                                    .addComponent(toTextField)
                                    .addComponent(priceTextField)
                                    .addComponent(planeNameTextField))))))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(backBtn)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(airlinerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(planeNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(fromTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(toTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(morningBtn)
                    .addComponent(eveningBtn)
                    .addComponent(nightBtn)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addComponent(addFlightBtn)
                .addContainerGap(504, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addFlightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFlightBtnActionPerformed
        // TODO add your handling code here:
        String id = idTextField.getText();  
        if(id == null || id.equals("")){
        JOptionPane.showMessageDialog(null, "Flight ID can't be empty");
        return;
        }
        
        
        
        String date = dateTextField.getText();  
        if(date == null || date.equals("")){
        JOptionPane.showMessageDialog(null, "Date can't be empty");
        return;
        }
        
        String from = fromTextField.getText();  
        if(from == null || from.equals("")){
        JOptionPane.showMessageDialog(null, "Source can't be empty");
        return;
        }
        
        String to = toTextField.getText();  
        if(to == null || to.equals("")){
        JOptionPane.showMessageDialog(null, "Destination can't be empty");
        return;
        }
        
        String price = priceTextField.getText();
        if(price == null || price.equals("")){
        JOptionPane.showMessageDialog(null, "Price can't be empty");
        return;
        }
        String planeName = planeNameTextField.getText();
       // String status = statusTextField.getText();
        try{
               Integer.parseInt(priceTextField.getText());
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null,"Enter number for Price");
                return;
            }
        
        if(morningBtn.isSelected()== false && eveningBtn.isSelected() == false && nightBtn.isSelected() == false ){
            JOptionPane.showMessageDialog(null,"Please select the Departure Time");
            return;
        }
        
        
        /*Calendar cal = Calendar.getInstance();
        cal.setLenient(false);
        cal.setTime();
        try {
            cal.getTime();
        }
        catch (Exception e) {
        System.out.println("Invalid date");
        }
        
        */
        
        final String DATE_FORMAT = "dd/MM/20yy";
        try {
            DateFormat df = new SimpleDateFormat(DATE_FORMAT);
            df.setLenient(false);
            df.parse(dateTextField.getText());
            
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null,"Invalid Date");
            return;
        }
        
       
        
        Flights flight = flightScheDirectory.addFlight();
        
        flight.setAirlinerName(airlinerTextField.getText());
        flight.setAirplaneName(planeNameTextField.getText());
        flight.setFlightName(idTextField.getText());
        flight.setDepDate(dateTextField.getText());
        flight.setDeparture(fromTextField.getText());
        flight.setArrive(toTextField.getText());
        flight.setPrice(Integer.parseInt(priceTextField.getText()));
        //flight.setStatus(statusTextField.getText());
        
        if(morningBtn.isSelected())
        {
            flight.setDepTime("MORNING");
        }
        if(eveningBtn.isSelected())
        {
            flight.setDepTime("EVENING");
        }
        if(nightBtn.isSelected())
        {
            flight.setDepTime("NIGHT");
        }
        
         JOptionPane.showMessageDialog(null,"Flight Created Successfully");
         airlinerTextField.setText("");
         planeNameTextField.setText("");
         idTextField.setText("");
         dateTextField.setText("");
         fromTextField.setText("");
         toTextField.setText("");
         priceTextField.setText("");
         morningBtn.setSelected(false);
         eveningBtn.setSelected(false);
         nightBtn.setSelected(false);
    
    }//GEN-LAST:event_addFlightBtnActionPerformed
    
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        
        rightJPanel.remove(this);
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.previous(rightJPanel);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFlightBtn;
    private javax.swing.JTextField airlinerTextField;
    private javax.swing.JButton backBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JRadioButton eveningBtn;
    private javax.swing.JTextField fromTextField;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton morningBtn;
    private javax.swing.JRadioButton nightBtn;
    private javax.swing.JTextField planeNameTextField;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JTextField toTextField;
    // End of variables declaration//GEN-END:variables
}
