/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.manageAirlinersJPanel;

import Business.Airliners;
import Business.Airplane;
import Business.AirplaneDirectory;
import Business.FlightScheDirectory;
import Business.Flights;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author adhar
 */
public class addPlaneJPanel extends javax.swing.JPanel {
     private JPanel rightJPanel;
    
    private Airliners airliner;
     private FlightScheDirectory flightScheDirectory;
     private AirplaneDirectory airplaneDirectory;

    /**
     * Creates new form addPlaneJPanel
     */
   

    
   addPlaneJPanel(JPanel rightJPanel, FlightScheDirectory flightScheDirectory, Airliners airliner, AirplaneDirectory airplaneDirectory) {
        initComponents();
             modNumTextField.setText("150");
           this.flightScheDirectory = flightScheDirectory;
           this.airliner = airliner;
           this.rightJPanel = rightJPanel;
           this.airplaneDirectory = airplaneDirectory;//To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        planeNameTextField = new javax.swing.JTextField();
        planeIDTextField = new javax.swing.JTextField();
        modNumTextField = new javax.swing.JTextField();
        manYearTextField = new javax.swing.JTextField();
        addPlaneBtn = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setText("Airplane Name :");

        jLabel2.setText("Airplane ID :");

        jLabel3.setText("No of Seats :");

        jLabel4.setText("Manufacturing Year :");

        planeNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planeNameTextFieldActionPerformed(evt);
            }
        });

        modNumTextField.setEditable(false);
        modNumTextField.setEnabled(false);
        modNumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modNumTextFieldActionPerformed(evt);
            }
        });

        addPlaneBtn.setText("Add Airplane");
        addPlaneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlaneBtnActionPerformed(evt);
            }
        });

        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel5.setText("Add Airplane Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(planeIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(planeNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addPlaneBtn)
                    .addComponent(jLabel5))
                .addGap(220, 220, 220))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnBack)
                .addGap(58, 58, 58)
                .addComponent(jLabel5)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(planeNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(planeIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(modNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(manYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addComponent(addPlaneBtn)
                .addContainerGap(267, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void planeNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planeNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_planeNameTextFieldActionPerformed

    private void addPlaneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlaneBtnActionPerformed
        // TODO add your handling code here:
        
        String airplaneName = planeNameTextField.getText();  
        if(airplaneName == null || airplaneName.equals("")){
        JOptionPane.showMessageDialog(null, "Airplane Name can't be empty!");
        return;
        }
        String airplaneID = planeIDTextField.getText();  
        if(airplaneID == null || airplaneID.equals("")){
        JOptionPane.showMessageDialog(null, "Airplane ID can't be empty!");
        return;
        }
        
        String modNum = modNumTextField.getText();
        if(modNum == null || modNum.equals("") ){
        JOptionPane.showMessageDialog(null, "Model Number can't be empty!");
        return;
        }
        
        try{
               Integer.parseInt(modNumTextField.getText());
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null,"Enter number for Model Number!");
                return;
            }
        
        String manuYear = manYearTextField.getText();
        if(modNum == null || modNum.equals("") ){
        JOptionPane.showMessageDialog(null, "Manufacturing Year can't be empty!");
        return;
        }
        
        try{
               Integer.parseInt(manYearTextField.getText());
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null,"Manufacturing Year can't be empty!");
                return;
            }
        
        String noofseats = modNumTextField.getText();
        Airplane airp = airplaneDirectory.addPlane();
        {
        airp.setAirplaneName(airplaneName);
        airp.setAirplaneID(airplaneID);
        airp.setModelNumber(Integer.parseInt(modNumTextField.getText()));
        airp.setManuYear(Integer.parseInt(manYearTextField.getText()));
        JOptionPane.showMessageDialog(null,"Created Successfully");
        planeNameTextField.setText("");
        planeIDTextField.setText("");
        modNumTextField.setText("");
        manYearTextField.setText("");
    
    }                                            

    }//GEN-LAST:event_addPlaneBtnActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.rightJPanel.remove(this);
        CardLayout layout = (CardLayout) this.rightJPanel.getLayout();
        
        Component[] comps = this.rightJPanel.getComponents();
        for (Component comp : comps)
        {
            if (comp instanceof BtnManageJPanel){
                BtnManageJPanel manage = (BtnManageJPanel) comp;
                manage.populateTable1(airplaneDirectory,"al");
            }
        }layout.previous(rightJPanel);

/*       rightJPanel.remove(this);
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.previous(rightJPanel);*/

    }//GEN-LAST:event_btnBackActionPerformed

    private void modNumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modNumTextFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_modNumTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPlaneBtn;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField manYearTextField;
    private javax.swing.JTextField modNumTextField;
    private javax.swing.JTextField planeIDTextField;
    private javax.swing.JTextField planeNameTextField;
    // End of variables declaration//GEN-END:variables

}
