/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.manageAirlinersJPanel;

import Business.Airliners;
import Business.AirlinersDirectory;
import Business.FlightScheDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author hp
 */
public class createAirlinersJPanel extends javax.swing.JPanel {
    private JPanel rightJPanel;
    private AirlinersDirectory airlinersDirectory;
    private FlightScheDirectory flightScheDirectory;

    /**
     * Creates new form createAirlinersJPanel
     */
   

    createAirlinersJPanel(JPanel rightJPanel, AirlinersDirectory airlinersDirectory) {
        initComponents();
         this.airlinersDirectory = airlinersDirectory;
         this.rightJPanel = rightJPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFieldStrengthOfFlights = new javax.swing.JTextField();
        txtFieldHeadOfficeLocation = new javax.swing.JTextField();
        txtFieldAirlinersName = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        moderateFreqBtn = new javax.swing.JRadioButton();
        highFreqBtn = new javax.swing.JRadioButton();
        lowFreqBtn = new javax.swing.JRadioButton();
        regionJComboBox = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("CREATE AIRLINER");

        jLabel2.setText("Airliners Name :");

        jLabel3.setText("Strength of Flights :");

        jLabel4.setText("Frequency of Flights :");

        jLabel5.setText("Head Office Location :");

        jLabel6.setText("Region of Operation :");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnCreate.setText("CREATE ");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        buttonGroup1.add(moderateFreqBtn);
        moderateFreqBtn.setText("Moderate");

        buttonGroup1.add(highFreqBtn);
        highFreqBtn.setText("High");

        buttonGroup1.add(lowFreqBtn);
        lowFreqBtn.setText("Low");

        regionJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select the Region", "Asia", "North America", "South America", "Europe", "Africa", "Australia", "All regions" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(281, 281, 281))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2)))
                        .addGap(132, 132, 132)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lowFreqBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(moderateFreqBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(highFreqBtn))
                            .addComponent(txtFieldHeadOfficeLocation)
                            .addComponent(txtFieldStrengthOfFlights)
                            .addComponent(txtFieldAirlinersName)
                            .addComponent(regionJComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(385, 385, 385)
                        .addComponent(btnCreate))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtFieldHeadOfficeLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(regionJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addComponent(btnCreate)
                        .addContainerGap(256, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFieldAirlinersName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFieldStrengthOfFlights, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lowFreqBtn)
                            .addComponent(moderateFreqBtn)
                            .addComponent(highFreqBtn)
                            .addComponent(jLabel4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
       /*  rightJPanel.remove(this);
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.previous(rightJPanel);*/
     
         this.rightJPanel.remove(this);
        CardLayout layout = (CardLayout) this.rightJPanel.getLayout();
        
        Component[] comps = this.rightJPanel.getComponents();
        for (Component comp : comps)
        {
            if (comp instanceof BtnManageJPanel){
                BtnManageJPanel manage = (BtnManageJPanel) comp;
                manage.populateTable(airlinersDirectory,"all");
               // manage.populateTable(airlinersDirectory,"all");
            }
        }layout.previous(rightJPanel);

        
        /*rightJPanel.remove(this);
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.previous(rightJPanel);*/
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        
        //int strength = Integer.parseInt(txtFieldStrengthOfFlights.getText());
        
       
        String airlinersName = txtFieldAirlinersName.getText();  
        if(airlinersName == null || airlinersName.equals("")){
        JOptionPane.showMessageDialog(null, "Airliner Name can't be empty!");
        return;
        }
        
        String s = txtFieldStrengthOfFlights.getText();
        if(s == null || s.equals("") ){
        JOptionPane.showMessageDialog(null, "Strength can't be empty!");
        return;
        }
        
        try{
               Integer.parseInt(txtFieldStrengthOfFlights.getText());
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null,"Enter number for Strength!");
                return;
            }
       
        
         if(lowFreqBtn.isSelected()== false && moderateFreqBtn.isSelected() == false && highFreqBtn.isSelected() == false ){
            JOptionPane.showMessageDialog(null,"Please select the Frequency of Flights");
            return;
        } 
         
        
        String headOffice = txtFieldHeadOfficeLocation.getText();
        if(headOffice == null || headOffice.equals("")){
        JOptionPane.showMessageDialog(null, "Head Office location can't be empty");
        return;
        }
       
        String x = String.valueOf(regionJComboBox.getSelectedItem());
        if(x.equalsIgnoreCase("Select the region"))
        {
            JOptionPane.showMessageDialog(null, "Please select the Region of Operations");
            return;
        } 
        
        
        
        Airliners f1 = airlinersDirectory.add();
        f1.setAirlinersName(airlinersName);
        f1.setStrengthofFlights(Integer.parseInt(txtFieldStrengthOfFlights.getText()));
        if(lowFreqBtn.isSelected())
        {
            f1.setFreqOfFlights("LOW");
        }
        
        else if(moderateFreqBtn.isSelected())
        {
            f1.setFreqOfFlights("MODERATE");
        }
        
        else if(highFreqBtn.isSelected())
        {
            f1.setFreqOfFlights("HIGH");
        }
       
        f1.setHeadOffice(headOffice);
        f1.setRegionOfOperations(x);
        
        JOptionPane.showMessageDialog(null, "Airliner added successfully");
        txtFieldAirlinersName.setText("");
        txtFieldHeadOfficeLocation.setText("");
        txtFieldStrengthOfFlights.setText("");
        lowFreqBtn.setSelected(false);
        moderateFreqBtn.setSelected(false);
        highFreqBtn.setSelected(false);
        regionJComboBox.setSelectedIndex(0);
        
    }//GEN-LAST:event_btnCreateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton highFreqBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton lowFreqBtn;
    private javax.swing.JRadioButton moderateFreqBtn;
    private javax.swing.JComboBox<String> regionJComboBox;
    private javax.swing.JTextField txtFieldAirlinersName;
    private javax.swing.JTextField txtFieldHeadOfficeLocation;
    private javax.swing.JTextField txtFieldStrengthOfFlights;
    // End of variables declaration//GEN-END:variables
}
