/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.manageAirlinersJPanel;

import Business.AirlinersDirectory;
import Business.FlightScheDirectory;
import Business.Flights;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rohan
 */
public class updateFlightJPanel extends javax.swing.JPanel {
    private JPanel rightJPanel;
    private AirlinersDirectory airlinersDirectory;
    private FlightScheDirectory flightScheDirectory;
    private Flights flights ;

    /**
     * Creates new form updateFlightJPanel
     */
    

    updateFlightJPanel(JPanel rightJPanel, FlightScheDirectory flightScheDirectory, Flights flight) {
        initComponents();
         this.flights = flight;
         this.airlinersDirectory = airlinersDirectory;
         this.rightJPanel = rightJPanel;
         this.flightScheDirectory = flightScheDirectory;
         populateUpdateFlightDetails();//To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        fromTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        priceTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        toTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        morningBtn = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        eveningBtn = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        nightBtn = new javax.swing.JRadioButton();
        idTextField = new javax.swing.JTextField();
        dateTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        airlinerTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        planeNameTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        fromTextField.setEnabled(false);

        jLabel3.setText("Flight ID");

        priceTextField.setEnabled(false);

        jLabel4.setText("Departure Time");

        toTextField.setEnabled(false);

        jLabel5.setText("Departure Date(DD/MM/YYYY)");

        jLabel6.setText("From ");

        buttonGroup1.add(morningBtn);
        morningBtn.setText("MORNING");
        morningBtn.setEnabled(false);

        jLabel7.setText("To");

        buttonGroup1.add(eveningBtn);
        eveningBtn.setText("EVENING");
        eveningBtn.setEnabled(false);

        jLabel8.setText("Price");

        buttonGroup1.add(nightBtn);
        nightBtn.setText("NIGHT");
        nightBtn.setEnabled(false);

        idTextField.setEnabled(false);

        dateTextField.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Update Flight");

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        jButton3.setText("<<Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("Airliner");

        jLabel9.setText("Airplane Name :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(updateBtn)
                                .addGap(29, 29, 29)
                                .addComponent(saveBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9))
                                .addGap(127, 127, 127)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idTextField)
                                    .addComponent(dateTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fromTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(toTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(priceTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(airlinerTextField)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(morningBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(eveningBtn)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nightBtn)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(planeNameTextField)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(361, 361, 361)
                        .addComponent(jLabel1)))
                .addGap(167, 167, 167))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(airlinerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(planeNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fromTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(toTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(morningBtn)
                    .addComponent(eveningBtn)
                    .addComponent(nightBtn)
                    .addComponent(jLabel4))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtn)
                    .addComponent(saveBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(288, 288, 288))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        
         String id = idTextField.getText();  
        if(id == null || id.equals("")){
        JOptionPane.showMessageDialog(null, "Flight ID can't be empty");
        return;
        }
        
        String plane = planeNameTextField.getText();
        
        String date = dateTextField.getText();  
        if(date == null || date.equals("")){
        JOptionPane.showMessageDialog(null, "Date can't be empty");
        return;
        }
        
        String from = fromTextField.getText();  
        if(from == null || from.equals("")){
        JOptionPane.showMessageDialog(null, "Source can't be empty");
        return;
        }
        
        String to = toTextField.getText();  
        if(to == null || to.equals("")){
        JOptionPane.showMessageDialog(null, "Destination can't be empty");
        return;
        }
        
        String price = priceTextField.getText();
        if(price == null || price.equals("")){
        JOptionPane.showMessageDialog(null, "Price can't be empty");
        return;
        }
        
        
        
        try{
               Integer.parseInt(priceTextField.getText());
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null,"Enter number for Price");
                return;
            }
        
        if(morningBtn.isSelected()== false && eveningBtn.isSelected() == false && nightBtn.isSelected() == false ){
            JOptionPane.showMessageDialog(null,"Please select the Departure Time");
            return;
        }
        
        
        final String DATE_FORMAT = "dd/MM/yyyy";
        try {
            DateFormat df = new SimpleDateFormat(DATE_FORMAT);
            df.setLenient(false);
            df.parse(dateTextField.getText());
            
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null,"Invalid Date");
            return;
        }
        
        
        
        
        
        flights.setAirlinerName(airlinerTextField.getText());
        flights.setAirplaneName(planeNameTextField.getText());
        flights.setFlightName(idTextField.getText());
        flights.setDepDate(dateTextField.getText());
        flights.setDeparture(fromTextField.getText());
        flights.setArrive(toTextField.getText());
        flights.setPrice(Integer.parseInt(priceTextField.getText()));
        if(morningBtn.isSelected())
        {
            flights.setDepTime("MORNING");
        }
        if(eveningBtn.isSelected())
        {
            flights.setDepTime("EVENING");
        }
        if(nightBtn.isSelected())
        {
            flights.setDepTime("NIGHT");
        }
        
        JOptionPane.showMessageDialog(null,"FLight Created Successfully");
        idTextField.setEditable(false);
         planeNameTextField.setEditable(false);
        dateTextField.setEditable(false);
        fromTextField.setEditable(false);
        toTextField.setEditable(false);
        priceTextField.setEditable(false);
        idTextField.setEnabled(false);
        dateTextField.setEnabled(false);
        fromTextField.setEnabled(false);
        toTextField.setEnabled(false);
        priceTextField.setEnabled(false);
        morningBtn.setEnabled(false);
        eveningBtn.setEnabled(false);
        nightBtn.setEnabled(false);
        
        
    }//GEN-LAST:event_saveBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        planeNameTextField.setEditable(true);
        idTextField.setEditable(true);
        dateTextField.setEditable(true);
        fromTextField.setEditable(true);
        toTextField.setEditable(true);
        priceTextField.setEditable(true);
        idTextField.setEnabled(true);
        dateTextField.setEnabled(true);
        fromTextField.setEnabled(true);
        toTextField.setEnabled(true);
        priceTextField.setEnabled(true);
        morningBtn.setEnabled(true);
        eveningBtn.setEnabled(true);
        nightBtn.setEnabled(true);
    }//GEN-LAST:event_updateBtnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
                
                           
        this.rightJPanel.remove(this);
        CardLayout layout = (CardLayout) this.rightJPanel.getLayout();
        
        Component[] comps = this.rightJPanel.getComponents();
        for (Component comp : comps)
        {
            if (comp instanceof viewAirlinersJPanel){
                viewAirlinersJPanel manage = (viewAirlinersJPanel) comp;
                manage.populateTable(flightScheDirectory,"all");
            }
        }layout.previous(rightJPanel);
    }//GEN-LAST:event_jButton3ActionPerformed
    private void populateUpdateFlightDetails() 
    {
    airlinerTextField.setText(flights.getAirlinerName());
    planeNameTextField.setText(flights.getAirplaneName());
    idTextField.setText(flights.getFlightName());
    dateTextField.setText(flights.getDepDate());
    fromTextField.setText(flights.getDeparture());
    toTextField.setText(flights.getArrive());
    priceTextField.setText(String.valueOf(flights.getPrice()));
  /*  if(morningBtn.isSelected())
        {
            flights.setDepTime("MORNING");
        }
        if(eveningBtn.isSelected())
        {
            flights.setDepTime("EVENING");
        }
        if(nightBtn.isSelected())
        {
            flights.setDepTime("NIGHT");
        }
        
     */   
     
     if(flights.getDepTime()=="MORNING" ){
            morningBtn.setSelected(true);
            eveningBtn.setEnabled(false);
            nightBtn.setEnabled(false);
        }
     
     else if(flights.getDepTime()=="EVENING"){
            morningBtn.setEnabled(false);
            eveningBtn.setSelected(true);
            nightBtn.setEnabled(false);
     }
     
     else if(flights.getDepTime()=="NIGHT"){
            morningBtn.setEnabled(false);
            eveningBtn.setEnabled(false);
            nightBtn.setSelected(true);
     }
         
         
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField airlinerTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JRadioButton eveningBtn;
    private javax.swing.JTextField fromTextField;
    private javax.swing.JTextField idTextField;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton morningBtn;
    private javax.swing.JRadioButton nightBtn;
    private javax.swing.JTextField planeNameTextField;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField toTextField;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
