/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.ManageTravelAgency;

import Business.*;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userInterface.CustomerBooking.bestFlightJPanel;

/**
 *
 * @author hp
 */
public class mngTravelAgencyFrontPageJPanel extends javax.swing.JPanel {
    public JPanel rightJPanel;
    public FlightScheDirectory flightScheDirectory;
    public PassengerDirectory passengerDirectory;
    public Flights flights;
    /**
     * Creates new form mngTravelAgencyFrontPageJPanel
     */
   
   

    public mngTravelAgencyFrontPageJPanel(JPanel rightJPanel, FlightScheDirectory flightScheDirectory,PassengerDirectory passengerDirectory) {
        initComponents(); 
        this.flightScheDirectory = flightScheDirectory;
        this.rightJPanel = rightJPanel; 
        this.passengerDirectory = this.passengerDirectory;//To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchFlightBtn = new javax.swing.JButton();
        listAllFlightsBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        searchFlightBtn.setText("Search Flight ");
        searchFlightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFlightBtnActionPerformed(evt);
            }
        });

        listAllFlightsBtn.setText("List All flights by Number");
        listAllFlightsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listAllFlightsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(358, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(searchFlightBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(listAllFlightsBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(332, 332, 332))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(searchFlightBtn)
                .addGap(49, 49, 49)
                .addComponent(listAllFlightsBtn)
                .addContainerGap(438, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchFlightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFlightBtnActionPerformed
        // TODO add your handling code here:
        searchFlightJPanel search = new searchFlightJPanel(rightJPanel, flightScheDirectory);
        rightJPanel.add("searchFlightJPanel", search );
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.next(rightJPanel);
        
    }//GEN-LAST:event_searchFlightBtnActionPerformed

    private void listAllFlightsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listAllFlightsBtnActionPerformed
        // TODO add your handling code here:
        listFlightJPanel list = new listFlightJPanel(rightJPanel, flightScheDirectory);
        rightJPanel.add("listFlightJPanel", list );
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_listAllFlightsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton listAllFlightsBtn;
    private javax.swing.JButton searchFlightBtn;
    // End of variables declaration//GEN-END:variables
}
