/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.ManageTravelAgency;

import Business.FlightScheDirectory;
import Business.Flights;
import Business.Seats;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adhar
 */
public class ViewJJPanel extends javax.swing.JPanel {
    private JPanel rightJPanel;
    private FlightScheDirectory flightScheDirectory;
    private Flights flights;

    /**
     * Creates new form ViewJJPanel
     */
   
    ViewJJPanel(JPanel rightJPanel, Flights flights, FlightScheDirectory flightScheDirectory) {
          initComponents(); 
          this.rightJPanel = rightJPanel;
          this.flights = flights;
          this.flightScheDirectory = flightScheDirectory;
          populateSeats();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        seatTable = new javax.swing.JTable();
        airlinerTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        eveningBtn = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        morningBtn = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        toTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        priceTextField = new javax.swing.JTextField();
        fromTextField = new javax.swing.JTextField();
        dateTextField = new javax.swing.JTextField();
        idTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nightBtn = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        planeNameTextField = new javax.swing.JTextField();

        seatTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Seat Number :", "Status", "Customer Name :"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(seatTable);

        airlinerTextField.setEnabled(false);

        jLabel6.setText("From ");

        eveningBtn.setText("EVENING");

        jLabel5.setText("Departure Date(DD/MM/YYY)");

        morningBtn.setText("MORNING");

        jLabel4.setText("Departure Time");

        jLabel3.setText("Flight ID");

        jLabel2.setText("Airliner");

        jLabel8.setText("Price");

        jLabel7.setText("To");

        nightBtn.setText("NIGHT");

        jLabel1.setText("Airplane Name :");

        planeNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planeNameTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel2)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(jLabel3)
                                .addComponent(jLabel1))
                            .addGap(224, 224, 224)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(airlinerTextField)
                                .addComponent(idTextField)
                                .addComponent(dateTextField)
                                .addComponent(fromTextField)
                                .addComponent(toTextField)
                                .addComponent(priceTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                .addComponent(planeNameTextField)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(jLabel4)
                            .addGap(143, 143, 143)
                            .addComponent(morningBtn)
                            .addGap(18, 18, 18)
                            .addComponent(eveningBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(nightBtn))))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(airlinerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(planeNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(fromTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(toTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(morningBtn)
                        .addComponent(eveningBtn)
                        .addComponent(nightBtn)))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void planeNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planeNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_planeNameTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField airlinerTextField;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JRadioButton eveningBtn;
    private javax.swing.JTextField fromTextField;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton morningBtn;
    private javax.swing.JRadioButton nightBtn;
    private javax.swing.JTextField planeNameTextField;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JTable seatTable;
    private javax.swing.JTextField toTextField;
    // End of variables declaration//GEN-END:variables

    private void populateSeats() {
        airlinerTextField.setText(flights.getAirlinerName());
        planeNameTextField.setText(flights.getAirplaneName());
        idTextField.setText(flights.getFlightName());
        dateTextField.setText(flights.getDepDate());
        fromTextField.setText(flights.getDeparture());
        toTextField.setText(flights.getArrive());
        priceTextField.setText(String.valueOf(flights.getPrice()));
        
         if(flights.getDepTime()=="MORNING" ){
            morningBtn.setSelected(true);
            eveningBtn.setEnabled(false);
            nightBtn.setEnabled(false);
        }
     
     else if(flights.getDepTime()=="EVENING"){
            morningBtn.setEnabled(false);
            eveningBtn.setSelected(true);
            nightBtn.setEnabled(false);
     }
     
     else if(flights.getDepTime()=="NIGHT"){
            morningBtn.setEnabled(false);
            eveningBtn.setEnabled(false);
            nightBtn.setSelected(true);
     }
        /*
        if(morningBtn.isSelected())
        {
            flights.setDepTime("MORNING");
        }
        if(eveningBtn.isSelected())
        {
            flights.setDepTime("EVENING");
        }
        if(nightBtn.isSelected())
        {
            flights.setDepTime("NIGHT");
        }
        */
        
        DefaultTableModel dtm = (DefaultTableModel) seatTable.getModel();
        dtm.setRowCount(0);
        for(Seats s: flights.getSeatList() )
        {
            Object row[]=new Object[3];
            row[0]=s;
            if(s.isBooked())
            {
                row[1]="Booked";
                row[2]= s.getName();
            }
            else
            {
                row[1]="Unbooked";
             
            }  
            dtm.addRow(row);
        } 
    }
}

