/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.ManageTravelAgency;

import Business.*;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author hp
 */
public class mngTravelAgencyFrontPageJPanel extends javax.swing.JPanel {
    private JPanel rightJPanel;
    private FlightScheDirectory flightScheDirectory;

    /**
     * Creates new form mngTravelAgencyFrontPageJPanel
     */
   
   

    public mngTravelAgencyFrontPageJPanel(JPanel rightJPanel, FlightScheDirectory flightScheDirectory) {
        initComponents(); 
        this.flightScheDirectory = flightScheDirectory;
        this.rightJPanel = rightJPanel;  //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchFlightBtn = new javax.swing.JButton();
        listAllFlightsBtn = new javax.swing.JButton();
        bookTicketBtn = new javax.swing.JButton();

        searchFlightBtn.setText("Search Flight ");
        searchFlightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFlightBtnActionPerformed(evt);
            }
        });

        listAllFlightsBtn.setText("List All flights by Number");
        listAllFlightsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listAllFlightsBtnActionPerformed(evt);
            }
        });

        bookTicketBtn.setText("Book Ticket");
        bookTicketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookTicketBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bookTicketBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listAllFlightsBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchFlightBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(460, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(searchFlightBtn)
                .addGap(38, 38, 38)
                .addComponent(listAllFlightsBtn)
                .addGap(48, 48, 48)
                .addComponent(bookTicketBtn)
                .addContainerGap(365, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchFlightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFlightBtnActionPerformed
        // TODO add your handling code here:
        searchFlightJPanel search = new searchFlightJPanel(rightJPanel, flightScheDirectory);
        rightJPanel.add("searchFlightJPanel", search );
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.next(rightJPanel);
        
    }//GEN-LAST:event_searchFlightBtnActionPerformed

    private void listAllFlightsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listAllFlightsBtnActionPerformed
        // TODO add your handling code here:
        listFlightJPanel list = new listFlightJPanel(rightJPanel, flightScheDirectory);
        rightJPanel.add("listFlightJPanel", list );
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_listAllFlightsBtnActionPerformed

    private void bookTicketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookTicketBtnActionPerformed
        // TODO add your handling code here:
        ticketBookingJPanel list = new ticketBookingJPanel(rightJPanel, flightScheDirectory);
        rightJPanel.add("ticketBookingJPanel", list );
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_bookTicketBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookTicketBtn;
    private javax.swing.JButton listAllFlightsBtn;
    private javax.swing.JButton searchFlightBtn;
    // End of variables declaration//GEN-END:variables
}
