/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.manageAirlinersJPanel;

import Business.Airliners;
import Business.AirlinersDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class manageAirlinersJPanel extends javax.swing.JPanel {
    private JPanel rightJPanel;
    private AirlinersDirectory airlinersDirectory;
    

    /**
     * Creates new form manageAirlinersJPanel
     */
   
    public manageAirlinersJPanel(JPanel rightJPanel, AirlinersDirectory airlinersDirectory) {
         //To change body of generated methods, choose Tools | Templates.
         initComponents();
        // this.airliners = airliners;
        
         this.airlinersDirectory = airlinersDirectory;
         this.rightJPanel = rightJPanel;
         populateTable(airlinersDirectory, "all");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAirliners = new javax.swing.JTable();
        createBtn = new javax.swing.JButton();
        viewBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        tblAirliners.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airliners Name :", "Strength of Flights :", "Frequency of Flights :", "Head Office Location :", "Region of Operations :"
            }
        ));
        jScrollPane1.setViewportView(tblAirliners);

        createBtn.setText("Create a new Airliners ");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        viewBtn.setText("View ");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("LIST");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(208, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(createBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(createBtn)
                .addGap(37, 37, 37)
                .addComponent(viewBtn)
                .addContainerGap(335, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        createAirlinersJPanel panel = new createAirlinersJPanel(rightJPanel, airlinersDirectory );
        rightJPanel.add("createAirlinersJPanel", panel);
        CardLayout layout = (CardLayout)rightJPanel.getLayout();
        layout.next(rightJPanel);
    }//GEN-LAST:event_createBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:
      //  DefaultTableModel dtm = (DefaultTableModel)tblAirliners.getModel();
        int selectedrow = tblAirliners.getSelectedRow();
        if (selectedrow >= 0)
        {
        Airliners airliner = (Airliners)tblAirliners.getValueAt(selectedrow,0);
        
        viewAirlinersJPanel panel = new viewAirlinersJPanel(rightJPanel, airliner );
        rightJPanel.add("viewAirlinersJPanel", panel);
        CardLayout layout = (CardLayout)rightJPanel.getLayout();
        layout.next(rightJPanel);
        }
      /*  int selectedRow = tblDetails.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a row from Table", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            Uber uber = (Uber) tblDetails.getValueAt((selectedRow), 0);
            ViewJPanel amPanel = new ViewJPanel (rightJPanel, uber);
            rightJPanel.add("ViewJPanel",amPanel);
            CardLayout layout = (CardLayout) rightJPanel.getLayout();
            layout.next(rightJPanel);
        }*/
       
      
    }//GEN-LAST:event_viewBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAirliners;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables

  

    void populateTable(AirlinersDirectory airlinersDirectory, String all) {
         DefaultTableModel dtm = (DefaultTableModel)tblAirliners.getModel();
        dtm.setRowCount(0);
        for ( Airliners air : airlinersDirectory.getAirlinersData())
        {
            Object row[]= new Object [5];
            row[0] = air.getAirlinersName();
            row[1] = air.getStrengthofFlights();
            row[2] = air.getFreqOfFlights();
            row[3] = air.getHeadOffice();
            row[4] = air.getRegionOfOperations();
            dtm.addRow(row);
            
            
        }
    }
}
