/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.manageAirlinersJPanel;

import Business.Airliners;
import Business.AirlinersDirectory;
import javax.swing.JPanel;

/**
 *
 * @author hp
 */
public class viewAirlinersJPanel extends javax.swing.JPanel {
    private JPanel rightJPanel;
    private Airliners airliners;
    //private AirlinersDirectory airlinersDirectory;
    /**
     * Creates new form viewAirlinersJPanel
     */
  

   

    viewAirlinersJPanel(JPanel rightJPanel, Airliners airliners) {
         initComponents();
         
       //  this.airlinersDirectory = airlinersDirectory;
         this.rightJPanel = rightJPanel;
         this.airliners = airliners;
         populateViewAirlinersDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFieldStrengthOfFlights = new javax.swing.JTextField();
        txtFieldFreqOfFlights = new javax.swing.JTextField();
        txtFieldHeadOfficeLocation = new javax.swing.JTextField();
        txtFieldAirlinersName = new javax.swing.JTextField();
        txtFieldRegionOfOperations = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();

        jLabel5.setText("Head Office Location :");

        jLabel6.setText("Region of Operations :");

        jLabel1.setText("VIEW ");

        jLabel2.setText("Airliners Name :");

        jLabel3.setText("Strength of Flights :");

        jLabel4.setText("Frequency of Flights :");

        updateBtn.setText("UPDATE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(137, 137, 137)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(127, 127, 127)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFieldRegionOfOperations, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtFieldHeadOfficeLocation, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtFieldAirlinersName, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtFieldStrengthOfFlights, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtFieldFreqOfFlights, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(371, 371, 371)
                        .addComponent(updateBtn)))
                .addContainerGap(306, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(txtFieldAirlinersName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFieldStrengthOfFlights, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFieldFreqOfFlights, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFieldHeadOfficeLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFieldRegionOfOperations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addComponent(updateBtn)
                .addContainerGap(285, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtFieldAirlinersName;
    private javax.swing.JTextField txtFieldFreqOfFlights;
    private javax.swing.JTextField txtFieldHeadOfficeLocation;
    private javax.swing.JTextField txtFieldRegionOfOperations;
    private javax.swing.JTextField txtFieldStrengthOfFlights;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables

    private void populateViewAirlinersDetails() {
         txtFieldAirlinersName.setText(airliners.getAirlinersName());
         txtFieldStrengthOfFlights.setText(String.valueOf(airliners.getStrengthofFlights()));
         txtFieldFreqOfFlights.setText(airliners.getFreqOfFlights());
         txtFieldHeadOfficeLocation.setText(airliners.getHeadOffice());
         txtFieldRegionOfOperations.setText(airliners.getRegionOfOperations());
    }
}
